from . import client
from . import nationalite
from . import propriete
from . import categorie_propriete
from . import piece_jointe
from . import piece_jointe_client
from . import dossier
from . import phase
from . import acte
from . import paiement
from . import historique_phase
from . import res_config_settings
from . import piece_jointe_propriete
from . import piece_jointe_dossier
from . import board
from . import custom_board
from . import relation_acheteur_vendeur
from . import conservation_fonciere
from . import ville